services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=deriv
      - SECRET_KEY=your-super-secret-key-change-in-production-docker
    depends_on:
      - mongodb
    ports:
      - '8000:8000'
  frontend:
    working_dir: /app
    image: node:20-alpine
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - '5173:5173'
    depends_on:
      - backend
volumes:
  mongo_data:


