services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Ollama service for local AI models
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*

  # AI Model Manager service
  ai-model-manager:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.ai-models
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=ollama:11434
      - MODEL_DOWNLOAD_ENABLED=true
    depends_on:
      - ollama
    volumes:
      - ai_models_data:/app/models
    command: python -m app.ai.model_manager

  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=deriv
      - SECRET_KEY=your-super-secret-key-change-in-production-docker
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=ollama:11434
      - LOCAL_AI_ENABLED=true
      - DEFAULT_AI_MODEL=phi-3-mini
    depends_on:
      - mongodb
      - redis
      - ollama
    ports:
      - '8000:8000'

  celery-worker:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=deriv
      - SECRET_KEY=your-super-secret-key-change-in-production-docker
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=ollama:11434
      - LOCAL_AI_ENABLED=true
      - DEFAULT_AI_MODEL=phi-3-mini
    depends_on:
      - mongodb
      - redis
      - ollama
    command: celery -A app.workers.celery_app worker --loglevel=info --queues=market_scan,position_monitor,trading,risk_monitor,signals,training,analysis

  celery-beat:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=deriv
      - SECRET_KEY=your-super-secret-key-change-in-production-docker
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=ollama:11434
      - LOCAL_AI_ENABLED=true
      - DEFAULT_AI_MODEL=phi-3-mini
    depends_on:
      - mongodb
      - redis
      - ollama
    command: celery -A app.workers.celery_app beat --loglevel=info

  frontend:
    working_dir: /app
    image: node:20-alpine
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo_data:
  redis_data:
  ollama_data:
  ai_models_data:
